### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 2556: invalid start byte

### ISSUE THREAD

**Issue by Anery** [togethercomputer/RedPajama-Data#42]
Another question, plz. I met an error in hashing step. Have you ever seen this before? 
```
Failed job 34548 (4 / 60): Job (task=0) failed during processing with trace:
----------------------
Traceback (most recent call last):
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/submitit/core/submission.py", line 54, in process_job
    result = delayed.result()
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/submitit/core/utils.py", line 133, in result
    self._result = self.function(*self.args, **self.kwargs)
  File "/disk2/RedPajama-Data/data_prep/cc/cc_net/cc_net/mine.py", line 275, in _hashes_shard
    jsonql.run_pipes(
  File "/disk2/RedPajama-Data/data_prep/cc/cc_net/cc_net/jsonql.py", line 455, in run_pipes
    write_jsons(data, output)
  File "/disk2/RedPajama-Data/data_prep/cc/cc_net/cc_net/jsonql.py", line 496, in write_jsons
    for res in source:
  File "/disk2/RedPajama-Data/data_prep/cc/cc_net/cc_net/jsonql.py", line 284, in map
    for x in source:
  File "/disk2/RedPajama-Data/data_prep/cc/cc_net/cc_net/process_wet_file.py", line 235, in __iter__
    for doc in parse_warc_file(self.open_segment(segment), self.min_len):
  File "/disk2/RedPajama-Data/data_prep/cc/cc_net/cc_net/process_wet_file.py", line 160, in parse_warc_file
    for doc in group_by_docs(lines):
  File "/disk2/RedPajama-Data/data_prep/cc/cc_net/cc_net/process_wet_file.py", line 133, in group_by_docs
    for warc in warc_lines:
  File "/disk2/RedPajama-Data/data_prep/cc/cc_net/cc_net/jsonql.py", line 971, in _close_when_exhausted
    yield from file
  File "/root/anaconda3/envs/py38/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 2556: invalid start byte
```

**Comment by Anery** [comment]
I have solved it. There was an unknown corruption while downloading the .gz data.
